### ISSUE TITLE
Exception thrown when finishing the min_error condition

### ISSUE THREAD

**Issue by cgled** [bmontambault/Active-Learning#10]
I couldn't reproduce this -- perhaps some kind of race condition?

URL was:

    http://activelearning.pythonanywhere.com/?sessionId=81925d29-53a0-48b7-8feb-35ee26873479&gi=2&fi=1

I was able to reproduce it locally, but it didn't work with a different sessionId. Not sure what the cause is.

    http://localhost:5000/?sessionId=81925d29-53a0-48b7-8feb-35ee26873479&gi=2&fi=1

Here's the trace:

```
[2017-07-11 11:15:22,805] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Users/clucas/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/clucas/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/clucas/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/clucas/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/clucas/anaconda/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_app.py", line 72, in start
    return task(goal,function_name,index)
  File "flask_app.py", line 122, in task
    raise ValueError('stop')
```

**Comment by bmontambault** [comment]
I couldn't reproduce this either, but the error comes from failing to convert a string to a float. This shouldn't happen, but if it does it will now just ignore the exception. At that point we'll see a string where it shouldn't be in the results and we can deal with it then.
